# Change these first
owner: RIT-RC # Your GitHub organization or username, where this repository lives
repo: rc-status-page # The name of this repository

sites:
  - name: RC Website
    url: $URL_RC_WEBSITE
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - aweits
  - name: SPORC-Cluster
    check: "tcp-ping"
    url: $IP_SPORC_CLUSTER
    port: 22
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - EmilioD
      - qwertos
      - aweits
      - paulmezz
      - meyersbs
      - kirkmanne
      - sidpbury
      - archxlith
      - merced317
      - "rc-admins"
  - name: KGCOE-GitLab
    check: "tcp-ping"
    url: $IP_KGCOE_GITLAB
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - qwertos
  - name: Mirrors
    url: $URL_MIRRORS
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - paulmezz
  - name: RC Documentation
    url: $URL_RC_DOCUMENTATION
    __dangerous__insecure: true # Ignore SSL cert error
    maxResponseTime: 60000
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - meyersbs
  - name: Open OnDemand
    check: "tcp-ping"
    url: $IP_OPEN_ONDEMAND
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - EmilioD
  - name: RC Ticketing
    url: $URL_RC_TICKETING
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - EmilioD
      - qwertos
      - meyersbs
  - name: Grafana
    check: "tcp-ping"
    url: $IP_GRAFANA
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - EmilioD
  - name: Virtualization
    check: "tcp-ping"
    url: $IP_VIRTUALIZATION
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - EmilioD
  - name: RC File Hosting
    url: $URL_PEOPLE
    icon: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-favicon.png
    assignees:
      - paulmezz

workflowSchedule:
  # 12AM Every Day - Generate response time graphs
  graphs: "0 0 * * *"
  # 11PM Every Day - Record response time of each endpoint
  responseTime: "0 23 * * *"
  # 1AM Every Day - Build and deploy website
  # Also runs every time files change
  staticSite: "0 1 * * *"
  # 12AM Every Day - Update README
  summary: "0 0 * * *"
  # 12AM Every Saturday - Update to newest version of upptime
  updateTemplate: "0 0 * * 6"
  # 3AM Every Day - 
  updates: "0 3 * * *"
  # Every 5 Minutes - Check endpoint statuses
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /rc-status-page
  logoUrl: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit_logo.svg
  themeUrl: https://cdn.statically.io/gh/rit-rc/rc-status-page/master/assets/rit-rc-theme.css
  skipDescriptionUpdate: true
  #skipHomepageUpdate: true
  name: Research Computing Status Page
  introTitle: "**RIT Research Computing Status Page**"
  introMessage: This page will tell you the status of RC services. If you're having trouble with a service and the issue is **not** documented below, please contact us at [rc-help@rit.edu](mailto:rc-help@rit.edu).
  navbar:
    - title: Status
      href: /
    - title: Contact Us
      href: mailto:rc-help@rit.edu
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
